apiVersion: apps/v1
kind: Deployment
metadata:
  name: harness-nginx
  namespace: {{ .Values.namespace }}    # substituted from values.yaml
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: harness-nginx
  template:
    metadata:
      labels:
        app: harness-nginx
    spec:
      containers:
      - name: nginx
        image: {{ .Values.image }}
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.namespace }}    # substituted from values.yaml
spec:
  type: {{ .Values.service.type }}
  selector:
    app: harness-nginx
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 80
